<table class="leftNavMenu" width="150" cellspacing="1" cellpadding="1" border="1">
	<tr>
		<td><a href="/springapp/index.jsp">Home</a></td>
	</tr>
	<tr>
		<td><a href="/springapp/application/events.jsp">Events</a></td>
	</tr>
	<tr>
		<td><a href="/springapp/application/members.jsp">Members</a></td>
	</tr>
	<tr>
		<td><a href="/springapp/application/crescentgirls.jsp">Crescent Girls</a></td>
	</tr>
	<tr>
		<td><a href="/springapp/application/sports.jsp">Sports</a></td>
	</tr>
	<tr>
		<td><a href="/springapp/application/resources.jsp">Resources</a></td>
	</tr>
	<tr>
		<td><a href="/springapp/index.jsp">Item</a></td>
	</tr>
</table>	
