<table class="leftNavMenu" width="150" cellspacing="1" cellpadding="1" border="1">
	<tr>
		<td><a href="localhost:8080//springapp/WebContent/application/hello.jsp">Home</a></td>
	</tr>
	<tr>
		<td><a href="localhost:8080/springapp/WebContent/application/hello.jsp">Events</a></td>
	</tr>
	<tr>
		<td><a href="localhost:8080/springapp/WebContent/application/hello.jsp">Members</a></td>
	</tr>
	<tr>
		<td><a href="localhost:8080/springapp/WebContent/application/hello.jsp">Crescent Girls</a></td>
	</tr>
	<tr>
		<td><a href="localhost:8080/springapp/WebContent/application/hello.jsp">Sports</a></td>
	</tr>
	<tr>
		<td><a href="localhost:8080/springapp/WebContent/application/hello.jsp">Resources</a></td>
	</tr>
	<tr>
		<td><a href="localhost:8080/springapp/WebContent/application/hello.jsp">Item</a></td>
	</tr>
</table>	
